apiVersion: v1
kind: Service
metadata:
  name: frontend-challenge
spec:
  type: NodePort
  selector:
    app: frontend-challenge
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
