# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: pipeline CI/CD

on:
  push:
    branches: [ "prueba2" ]
  pull_request:
    branches: [ "prueba2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t juandiegosicacha/frontend-challenge2:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag juandiegosicacha/frontend-challenge2:latest ${{ secrets.DOCKER_USERNAME }}/juandiegosicacha/frontend-challenge2:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/juandiegosicacha/frontend-challenge2:latest
